CREATE TABLE ITEM (
  "ID" BIGINT  PRIMARY KEY AUTO_INCREMENT,
  "NAME" varchar(50)  NOT NULL,
  "PRICE" INTEGER NOT NULL,
  "DESCRIPTION" varchar(115) DEFAULT NULL
);
CREATE TABLE CATEGORY (
  "ID" INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  "NAME" varchar(50) NOT NULL,
  "ORDER" INTEGER NOT NULL
);
CREATE TABLE CATEGORY_ITEM (
  "CATEGORY_ID" INTEGER NOT NULL,
  "ITEM_ID" BIGINT NOT NULL,
  PRIMARY KEY ("ITEM_ID","CATEGORY_ID")
);
